name = "PortfolioAllocation"
uuid = "c318330a-411a-4c96-b1bf-4cc0219d852c"
authors = ["Sam Thorold <sam.thorold@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
